spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest-spring-boot?useTimezone=true&serverTimezone=UTC
    username: root
    password: admin123
  logging:
    level:
      root: INFO, ERROR, DEBUG
  jackson:
    serialization:
      write-dates-as-timestamps: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
      show-sql: false
spring-doc:
  pathsToMatch: /**/v1/**,/**/v2/**
  swagger-ui:
    use-root-path: true

