# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: CI with Github Actions

on:
  push:
    branches: 
    - "main"

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Set up JDK 20
      uses: actions/setup-java@v3
      with:
        java-version: '20'
        distribution: 'temurin'
    - name: Build Application JAR with Gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: clean build -
    - name: Docker Compose
      run: docker compose build
    - name: Push to Docker Hub
      run: |
       docker tag  ${{ secrets.DOCKER_USERNAME }}/rest-spring-boot:latest ${{ secrets.DOCKER_USERNAME }}/rest-spring-boot:${{ github.run_id }}
       docker push ${{ secrets.DOCKER_USERNAME }}/rest-spring-boot:${{ github.run_id }}
       docker push ${{ secrets.DOCKER_USERNAME }}/rest-spring-boot:latest


